# Generated by Django 3.1.11 on 2021-06-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='photo',
        ),
    ]
